### PR TITLE
FIX: Replace pickle with cloudpickle

### PR DESCRIPTION
**Pull request by effigies**
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] All tests passing
- [x] I have added tests to cover my changes
- [ ] I have updated documentation (if necessary)
- [x] My code follows the code style of this project 
(we are using `black`: you can `pip install pre-commit`, 
run `pre-commit install` in the `pydra` directory 
and `black` will be run automatically with each commit)

## Acknowledgment
- [x] I acknowledge that this contribution will be available under the Apache 2 license.

### CODE REVIEW

**Comment by effigies** [comment]
@djarecka I'm still getting failed tests, but elsewhere.

**Comment by djarecka** [comment]
Where?

Folks from cludpickle answered me, but they don't see the error...

**Comment by effigies** [comment]
It's no longer a pickling issue, but the tests still aren't passing for reasons I haven't had a chance to look into.

https://travis-ci.org/djarecka/pydra/jobs/56492690

**Comment by djarecka** [comment]
Ok, will look into it once i am at my laptop

**Comment by effigies** [comment]
This is in master, so you can just merge/rebase instead.

**Pull request closed without merging**
